name: Playwright Tests to run on VMs
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: ssh-scp-ssh-pipelines
      # You may pin to the exact commit or the version.
      # uses: cross-the-world/ssh-scp-ssh-pipelines@78e864b4890087a58248ff39320406971ca88b89
        uses: cross-the-world/ssh-scp-ssh-pipelines@v1.1.4
        with: 
          # ssh remote host
          host: 218.189.112.206
          # ssh remote user
          user: masoodahmed
          # content of ssh private key. ex raw content of ~/.ssh/id_rsa
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          # command to be executed
          command: "cd /Users/masoodahmed/Desktop/fwd-playwright-cicd && npm run test"
    # - name: Run tests on machine 2
    #   uses: D3rHase/ssh-command-action@v0.2.2
    #   with:
    #     # hostname / IP of the server
    #     host: 218.189.112.206
    #     # user of the server
    #     user: masoodahmed
    #     # private ssh key registered on the server
    #     private_key: ${{ secrets.SSH_PRIVATE_KEY }}
    #     # command to be executed
    #     command: "cd /Users/masoodahmed/Desktop/fwd-playwright-cicd && npm run test"


        

# #- name: SSH Command
#   # You may pin to the exact commit or the version.
#   # uses: D3rHase/ssh-command-action@51ec3cec93e9557d7a5289c1e31a4a28185e5200
#   uses: D3rHase/ssh-command-action@v0.2.2
#   with:
#     # hostname / IP of the server
#     host: 
#     # ssh port of the server
#     port: # optional, default is 22
#     # user of the server
#     user: 
#     # private ssh key registered on the server
#     private_key: 
#     # Fingerprint of the server, preventing man-in-the-middle attacks
#     host_fingerprint: # optional
#     # command to be executed
#     command: # optional, default is echo 'Hello world'



# name: Playwright Tests
# on:
#   push:
#     branches: [ main, master ]
#   pull_request:
#     branches: [ main, master ]
# jobs:
#   test:
#     timeout-minutes: 60
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v3
#     - uses: actions/setup-node@v3
#       with:
#         node-version: 16
#     - name: Install dependencies
#       run: npm ci
#     - name: Install Playwright Browsers
#       run: npx playwright install --with-deps
#     - name: Run Playwright tests
#       run: npx playwright test
#     - uses: actions/upload-artifact@v3
#       if: always()
#       with:
#         name: playwright-report
#         path: playwright-report/
#         retention-days: 30
